# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: astarteplatform/msghub/message_hub_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from astarteplatform.msghub import astarte_message_pb2 as astarteplatform_dot_msghub_dot_astarte__message__pb2
from astarteplatform.msghub import message_hub_error_pb2 as astarteplatform_dot_msghub_dot_message__hub__error__pb2
from astarteplatform.msghub import node_pb2 as astarteplatform_dot_msghub_dot_node__pb2
from astarteplatform.msghub import interface_pb2 as astarteplatform_dot_msghub_dot_interface__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0astarteplatform/msghub/message_hub_service.proto\x12\x16\x61starteplatform.msghub\x1a\x1bgoogle/protobuf/empty.proto\x1a,astarteplatform/msghub/astarte_message.proto\x1a.astarteplatform/msghub/message_hub_error.proto\x1a!astarteplatform/msghub/node.proto\x1a&astarteplatform/msghub/interface.proto\"\x87\x01\n\x10MessageHubResult\x12/\n\rempty_message\x18\x01 \x01(\x0b\x32\x16.google.protobuf.EmptyH\x00\x12\x38\n\x05\x65rror\x18\x02 \x01(\x0b\x32\'.astarteplatform.msghub.MessageHubErrorH\x00\x42\x08\n\x06result2\xdd\x03\n\nMessageHub\x12X\n\x06\x41ttach\x12\x1c.astarteplatform.msghub.Node\x1a,.astarteplatform.msghub.AstarteMessageResult\"\x00\x30\x01\x12Z\n\x04Send\x12&.astarteplatform.msghub.AstarteMessage\x1a(.astarteplatform.msghub.MessageHubResult\"\x00\x12L\n\x06\x44\x65tach\x12\x16.google.protobuf.Empty\x1a(.astarteplatform.msghub.MessageHubResult\"\x00\x12\x63\n\rAddInterfaces\x12&.astarteplatform.msghub.InterfacesJson\x1a(.astarteplatform.msghub.MessageHubResult\"\x00\x12\x66\n\x10RemoveInterfaces\x12&.astarteplatform.msghub.InterfacesName\x1a(.astarteplatform.msghub.MessageHubResult\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'astarteplatform.msghub.message_hub_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGEHUBRESULT']._serialized_start=275
  _globals['_MESSAGEHUBRESULT']._serialized_end=410
  _globals['_MESSAGEHUB']._serialized_start=413
  _globals['_MESSAGEHUB']._serialized_end=890
# @@protoc_insertion_point(module_scope)
